port 26379
dir /tmp
requirepass sentinel_secret_pass
sentinel resolve-hostnames yes
sentinel monitor mymaster kvrocks-sentinel-master 6666 1
sentinel auth-pass mymaster kvrocks_secret_pass
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 6000
sentinel parallel-syncs mymaster 1
